# Generated by Django 5.1 on 2024-08-14 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of animal category')),
                ('description', models.TextField(max_length=1000, verbose_name='Description of animal category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of animal')),
                ('scientific_name', models.CharField(max_length=200, verbose_name='Scientific name')),
                ('description', models.TextField(max_length=2000, verbose_name='Description of animal')),
                ('habitat', models.TextField(max_length=2000, verbose_name='Habitat of animal')),
                ('diet', models.TextField(max_length=2000, verbose_name='Diet of animal')),
                ('conservation_status', models.CharField(max_length=200, verbose_name='Status of conservation')),
                ('image', models.ImageField(upload_to='animals/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.animalcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title of Post')),
                ('content', models.TextField(max_length=2000, verbose_name='Content written by user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excerpt', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('status', models.CharField(blank=True, choices=[('a', 'Draft'), ('b', 'Published')], default='a', help_text='Status', max_length=1)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='animals.animal')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='animals.tag')),
            ],
        ),
    ]
