# Generated by Django 5.1 on 2024-08-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='tags',
            new_name='tag',
        ),
    ]
