# Generated by Django 5.1 on 2024-08-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_rename_tags_blogpost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Image'),
        ),
    ]
