# Generated by Django 5.1 on 2024-08-22 06:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='animalcategory',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
