# Generated by Django 5.1 on 2024-08-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_alter_animal_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='conservation_status',
            field=models.TextField(max_length=200, verbose_name='Status of conservation'),
        ),
    ]
