# Generated by Django 5.1 on 2024-08-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_remove_blogpost_excerpt_remove_blogpost_views_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
