# Generated by Django 5.1 on 2024-08-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_alter_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='category',
        ),
        migrations.AddField(
            model_name='animal',
            name='category',
            field=models.ManyToManyField(help_text='Aprašykime gyvūnus priklausančius kategorijai', to='animals.animalcategory'),
        ),
    ]
